name: "Coverity"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # At 08:00 UTC daily.

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

jobs:
  scan:
    name: "Scan"
    runs-on: "ubuntu-24.04"
    if: ${{ github.repository_owner == 'openbgpd-portable' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install libevent-dev

      - name: "Download Coverity build tool"
        env:
          PROJECT: "openbgpd-portable/openbgpd-portable"
          COVERITY_SCAN_TOKEN: "${{ secrets.COVERITY_SCAN_TOKEN }}"
        run: |
          wget -nv https://scan.coverity.com/download/linux64 --post-data "token=$COVERITY_SCAN_TOKEN&project=$PROJECT" -O coverity_tool.tar.gz
          mkdir coverity_tool
          tar xzf coverity_tool.tar.gz --strip 1 -C coverity_tool

      - name: "Setup"
        run: |
          ./autogen.sh
          ./configure

      - name: "Build with Coverity build tool"
        run: |
          export PATH=`pwd`/coverity_tool/bin:$PATH
          cov-build --dir cov-int make

      - name: "Submit build result to Coverity Scan"
        env:
          EMAIL: "job@openbsd.org"
          PROJECT: "openbgpd-portable/openbgpd-portable"
          COVERITY_SCAN_TOKEN: "${{ secrets.COVERITY_SCAN_TOKEN }}"
        run: |
          tar czvf cov.tar.gz cov-int
          curl --form token=$COVERITY_SCAN_TOKEN \
            --form email=$EMAIL \
            --form file=@cov.tar.gz \
            --form version="Commit $GITHUB_SHA" \
            --form description="Build submitted via CI" \
            https://scan.coverity.com/builds?project=$PROJECT
